### ISSUE TITLE
Const char error? [Solved - just use startx]

### ISSUE THREAD

**Issue by TymekBrunka** [collinalexbell/HackMatrix#76]
so when starting with /home/tymek/HackMatrix/matrix it prints out const char* error

image to be posted soon.

**Comment by TymekBrunka** [comment]
![Uploading Screenshot_2024-06-08-20-02-13-631_lockscreen.jpg…]()

**Comment by TymekBrunka** [comment]
Yes, it gives no more information on what is the error, it works the same on dm and tty

and whould xinit fix it?

**Comment by collinalexbell** [comment]
You have to run the program in xinit.

**Comment by TymekBrunka** [comment]
why xinit and not like script in greetd

oh, i thouth it can be downloaded at least bc there was add attachment button and that's what i used.

and error msg in screenshot is:

Failed to open display
terminate called after throwing an instance of 'char const*'

**Comment by collinalexbell** [comment]
I've never used greetd. Seems like it is mostly used for Wayland compositors. I wouldn't know how to start an x server from it.

**Comment by collinalexbell** [comment]
Doesn't seem like your method is properly starting an xserver.

I just put my config in .xinitrc and run startx in the tty

**Comment by TymekBrunka** [comment]
Can I use `xinit` in dm?

**Comment by TymekBrunka** [comment]
i guess i have same issue as https://github.com/collinalexbell/HackMatrix/issues/57 so i close it

**Comment by TymekBrunka** [comment]
*closes*
