### ISSUE TITLE
Immediately goes to a black screen and crashes

### ISSUE THREAD

**Issue by Saithe6** [collinalexbell/HackMatrix#87]
![image](https://github.com/user-attachments/assets/530ca2b3-2b41-4156-bbc4-94ab21c9fc5d)

I'm trying to use it on an arch linux virtual machine. It compiled fine and the binary is there, but for some reason it keeps crashing. I don't know if my .xinitrc is wrong or if it's some other issue

**Comment by jollysan** [comment]
can you cd into the hackmatrix directory and then try again?

**Comment by Saithe6** [comment]
my xinitrc is ```/home/saithe/HackMatrix/matrix```  I also tried putting exec in front of that, same thing

**Comment by Saithe6** [comment]
okay so I finally got it to launch. I had to have exactly
```
cd /home/saithe/HackMatrix/
/home/saithe/HackMatrix/matrix
```
previously I tried but with ./matrix as the second line

**Comment by collinalexbell** [comment]
You can probably do just `~/HackMatrix/matrix` as the path.

Also, you should probably call `exec ~/HackMatrix/matrix` in the comity
