### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by blacklightpy** [collinalexbell/HackMatrix#96]
I'm getting only 12 FPS at both 720p and 480p modes.

Intel Pentium Gold 4417U / Intel HD Graphics 620
12 GB RAM

Can run Crysis.

It used to be faster in a previous commit (May or so).

**Comment by collinalexbell** [comment]
I think this may be fixed.

**Comment by blacklightpy** [comment]
I'll rebuild and see

**Comment by blacklightpy** [comment]
Yes, it is very fast now.
